#!/bin/sh
####  PBS preamble

# Change the number of cores (ppn=1), amount of memory, and walltime:
#PBS -l nodes=1:ppn=16,walltime=48:00:00
#PBS –A mjf283_b_g_sc_covid

# Change "example_flux" to the name of your Flux allocation:
#PBS -A open
# export PROJ_LIB=/storage/home/luy70/.conda/envs/r-environment/share/proj
cd /storage/home/luy70/work/POMCP_CODE/Santiago2/Setup_2
module load python/3.6.3-anaconda5.0.1
# source activate r-environment
python3 examine_simulations_1.py
